name: CI/CD Microservices

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: [self-hosted, label-1]
    container:
      image: kamalakar2210/ci-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push adservice
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src/adservice
          push: true
          tags: |
            kamalakar2210/adservice:latest
            kamalakar2210/adservice:${{ env.SHORT_SHA }}-${{ github.run_number }}
